title: YnChuan Blog
email: wangxunxun3094@qq.com
description: 
url: ""
github_username:  ynchuan 
baseurl: /blog
hoster: http://ynchuan.github.io/blog/
timezone: Asia/Shanghai 
paginate: 5
paginate_path: "page:num" 
permalink: /:year/:month/:title.html  
exclude: 
- darkkimochi
- assets/images/*.jpg
- yellowblue 
gems: 
- jekyll-archives
- jekyll-paginate 