title: YnChuan Blog
email: wangxunxun3094@qq.com
description: 
url: ""
github_username:  ynchuan
facebook_username:  axlyody
baseurl: /blog
timezone: Asia/Shanghai
permalink: /:year/:month/:title.html 

exclude: 
- darkkimochi
- assets/images/*.jpg
- yellowblue
paginate: 3
paginate_path: "page/:num"
gems: 
- jekyll-archives
- jekyll-paginate